apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: goapi
  name: goapi
  namespace: default
spec:
  selector:
    matchLabels:
      app: goapi
  template:
    metadata:
      labels:
        app: goapi
    spec:
      containers:
      - image: premsvmm/goapi:a84eec01e1a1c7172de510f89848f14ae23418c0
        imagePullPolicy: IfNotPresent
        name: goapi
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
