apiVersion: v1
kind: Service
metadata:
  labels:
    app: goapi
  name: goapi
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 30204
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: goapi
  type: LoadBalancer